# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a62d9e00ddc723a52b7f4af3bef27ba78d58c3b15d3e2e3df1317dc4a8cf73e7f03b77222d5fcdb1cfc1ad8e5b339dda26c5b696a8d33560c34c736b811dbd3

test:
  secret_key_base: d804e9aad556ce843b254de548078050220918333c16b7605a4c45cb61de5c0991a213d98810cb3cab4357b3489d70f4541c535f796cf03a4cd99e0e3046ebd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
